package edu.grinnell.csc207.soundsofsorting;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import edu.grinnell.csc207.soundsofsorting.events.*;

/**
 * A collection of sorting algorithms.
 */
public class Sorts {
    /**
     * Swaps indices <code>i</code> and <code>j</code> of array <code>arr</code>.
     * @param <T> the carrier type of the array
     * @param arr the array to swap
     * @param i the first index to swap
     * @param j the second index to swap
     */
    public static <T> void swap(T[] arr, int i, int j) {
        T tmp = arr[i];
        arr[i] = arr[j];
        arr[j] = tmp;
    }

    /**
     * Sorts the array according to the bubble sort algorithm:
     * <pre>
     * [ unprocessed | i largest elements in order ]
     * </pre>
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<T>> bubbleSort(T[] arr) {
        List<SortEvent<T>> events = new ArrayList<>();
        int length = arr.length;
        for (int i = 0; i < length; i++) {
            for (int j = 0; j < length - i - 1; j++) {
                if (arr[j].compareTo(arr[j + 1]) > 0)
                    swap(arr, j, j + 1);
            }
        }
        return events;
    }

    /**
     * Sorts the array according to the selection sort algorithm:
     * <pre>
     * [ i smallest elements in order | unprocessed ]
     * </pre>
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<T>> selectionSort(
            T[] arr) {
        List<SortEvent<T>> events = new ArrayList<>();
         for (int j = 0; j < arr.length; j++) {
            int tracker = j; // tracks largest element in unsorted region
            for (int i = j + 1; i < arr.length; i++) {
                if (arr[tracker].compareTo(arr[i]) > 0) {
                    tracker = i; // store new largest element in unsorted region
                }
            }
            swap(arr, tracker, j);
        }
        return events;
    }

    /**
     * Sorts the array according to the insertion sort algorithm:
     * <pre>
     * [ i elements in order | unprocessed ] 
     * </pre>
     * @param <T> the carrier type of the array
     * @param arr the array to sort
     * @return the sort events generated by this sort
     */
    public static <T extends Comparable<? super T>> List<SortEvent<T>> insertionSort(
            T[] arr) {
        List<SortEvent<T>> events = new ArrayList<>();
        for (int j = 0; j < arr.length; j++) {
            int i = 0;
            for (; i < j; i++) {
                if (arr[i].compareTo(arr[j]) > 0)
                    break;
            }
            T hold = arr[j];
            for (int w = j; w > i; w--) // shifts all elements between i and j to the right
            {
                swap(arr, w, w - 1);
            }
            arr[i] = hold; // moves element at j to i
        }
        return events;
    }

    /**
 * Sorts the array according to the merge sort algorithm.
 * @param <T> the carrier type of the array
 * @param arr the array to sort
 * @return the sort events generated by this sort
 */
public static <T extends Comparable<? super T>> List<SortEvent<T>> mergeSort(T[] arr) {
    List<SortEvent<T>> events = new ArrayList<>();
    T[] shadow = Arrays.copyOf(arr, arr.length);
    mergehelp(arr, shadow, 0, arr.length);
    return events;
}

public static <T extends Comparable<? super T>> void mergehelp(
        T[] arr, T[] shadow, int beg, int end) {
    if (end - beg <= 1) {
        return;
    }

    int mid = (beg + end) / 2;

    mergehelp(arr, shadow, beg, mid);
    mergehelp(arr, shadow, mid, end);

    int leftIn = beg;
    int rightIn = mid;
    int shadowIn = beg;

    while (leftIn < mid && rightIn < end) {
        if (arr[leftIn].compareTo(arr[rightIn]) <= 0) {
            shadow[shadowIn++] = arr[leftIn++];
        } else {
            shadow[shadowIn++] = arr[rightIn++];
        }
    }

    while (leftIn < mid) {
        shadow[shadowIn++] = arr[leftIn++];
    }

    while (rightIn < end) {
        shadow[shadowIn++] = arr[rightIn++];
    }

    for (int i = beg; i < end; i++) {
        arr[i] = shadow[i];
    }
}

/**
 * Sorts the array according to the quick sort algorithm.
 * @param <T> the carrier type of the array
 * @param arr the array to sort
 * @return the sort events generated by this sort
 */
public static <T extends Comparable<? super T>> List<SortEvent<T>> quickSort(T[] arr) {
    List<SortEvent<T>> events = new ArrayList<>();
    quickSort_help(arr, 0, arr.length - 1);
    return events;
}

public static <T extends Comparable<? super T>> void quickSort_help(T[] arr, int beg, int end) {

    if (beg >= end) {
        return;
    }

    int mid = (beg + end) / 2;
    swap(arr, mid, end);   // move pivot to end

    int leftpoint = beg;
    int rightpoint = end - 1;

    while (leftpoint <= rightpoint) {

        while (leftpoint <= rightpoint &&
               arr[leftpoint].compareTo(arr[end]) < 0) {
            leftpoint++;
        }

        while (leftpoint <= rightpoint &&
               arr[rightpoint].compareTo(arr[end]) >= 0) {
            rightpoint--;
        }

        if (leftpoint < rightpoint) {
            swap(arr, leftpoint++, rightpoint--);
        }
    }

    swap(arr, leftpoint, end);  // put pivot in correct place

    quickSort_help(arr, beg, leftpoint - 1);
    quickSort_help(arr, leftpoint + 1, end);
}
    /**
     * Sorts the given array by applying the given events to it, in sequence.
     * @param events the sorting events to apply
     * @param arr the array to sort
     */
    public static <T extends Comparable<? super T>> void eventSort(
        List<SortEvent<T>> events, T[] arr) {
        // TODO: implement me!
    }
}